name: Running bot
 
on: push

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         continue-on-error: true
         timeout-minutes: 5
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison ccache openjdk-8-jdk
            sudo -E apt-get install expect
            git config --global user.name "rui-ports"
            git config --global user.email "secrets.EMAILGIT"
            mkdir here &&cd here
            git clone https://github.com/rui-ports/ruigsi.git here

       - name: Setup 2.00 and seda
         continue-on-error: true
         timeout-minutes: 3
         run: |
            git clone --recurse-submodules https://${{ secrets.EMAIL }}":${{ secrets.PASSWORD }}"@github.com/rui-ports/ErfanGSIs.git
            sudo chmod -R 0777 ErfanGSIs
            sudo bash ErfanGSIs/setup.sh
            
       - name: Download BoboBot sources
         continue-on-error: true
         timeout-minutes: 5
         run: |
            sudo aria2c http://tdrive.manofuranium.workers.dev/BoboBot.jar

       - name: Generate value
         continue-on-error: true
         timeout-minutes: 3
         run: |
             java -jar BoboBot.jar
         
       - name: Add value
         continue-on-error: true
         timeout-minutes: 1
         run: |
             rm -rf configs/config.prop
             cd configs
             touch config.prop
             echo "#Bo³+t config file" >> "config.prop"
             echo "#Fri Jun 26 06:08:12 UTC 2020" >> "config.prop"
             echo "bot-username=${{ secrets.BOTUN }}" >> "config.prop"
             echo "bot-token=${{ secrets.BOTKEY }}" >> "config.prop"
             echo "bot-master=${{ secrets.USERKEY }}" >> "config.prop"
             
       - name: Run bobobot
         continue-on-error: true
         timeout-minutes: 340
         run: sudo java -jar BoboBot.jar
         
       - name: Test
         continue-on-error: true
         timeout-minutes: 1
         run: |
              cd here/here
              echo "1" >> push.txt
              git add .
              git commit -m "Loop workflow"
              
       - name: Rerun
         continue-on-error: true
         timeout-minutes: 5
         run: |
              cd here/here
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"qrovic\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"master -> master\"
              set timeout -10
              interact"
              
       
